= Super Cool Logger Service
Kamarul Kawnayeen;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlink:

[introduction]
= Introduction
RESTful services to manage all of your application logs at cloud.

[[overview]]
= Overview
This section will discuss the cross cutting concerns of all the services.

[[overview-http-verbs]]
== HTTP Verbs
Super Cool Logger Service tries to adhere as closely as possible to standard
HTTP and REST conventions in its use of HTTP verbs.
|===
| Verb | Usage

|'GET'
| Used to retrieve a resource

| 'POST'
| Used to create a new resource
|===

[[overview-http-status-cods]]
== HTTP status codes
Super Cool Logger Service tries to adhere as closely as possible to standard
HTTP and REST conventions in its use of HTTP status codes.

|===
| Status code | Usage

| '200 OK'
| Standard response for successful HTTP requests.
  The actual response will deped on the request method used.
  In a GET request, the response will contains an entity corresponding to requested resource

| '201 Created'
| The request has been fulfilled and resulted in a new source being created

| '401 Unauthorized'
| In BASIC authentication scheme, return in case of invalid credential

| '403 Forbidden'
| If token verification failed or rate limit exceeded
|===

[[authentication]]
== Authentication
All the end points are authenticated. The very starting api of logger service use
*_https://en.wikipedia.org/wiki/Basic_access_authentication[Basic Authentication]_*, where user
need to authenticate himself using *_username_* and *_password_*. If basic auth succeeded,
then it will return a *_https://jwt.io/[Json Web Token]_* which the
user need to provide in authorization header for each subsequent request.


[[services]]
= Services

[[services-auth]]
== Auth
This service is used to authenticate an user with username and password.
In case of valid credential it will return a JWT token. If credential is
invalid, it will return 401 Unauthorized

[[services-auth-valid]]
=== Valid credential
Access the auth service with valid credential:

include::{snippets}/auth-valid-credential/curl-request.adoc[]

Valid response will be:

include::{snippets}/auth-valid-credential/http-response.adoc[]

[[services-auth-invalid]]
=== Invalid or no credential
Access the auth service with no credential & invalid credential:

include::{snippets}/auth-no-credential/curl-request.adoc[]

include::{snippets}/auth-invalid-cred/curl-request.adoc[]

And the response will be

include::{snippets}/auth-no-credential/http-response.adoc[]

[[profile]]
== Profile
Here's how to access profile api

include::{snippets}/profile-success/http-request.adoc[]

And the response will be

include::{snippets}/profile-success/http-response.adoc[]

[[application]]
== Applications
End points regarding _Application_ resource

[[create-application]]
=== Create Application
This section will discuss how to create a new application & different
error message thrown when creating application

==== Valid Request

Access the register service with valid token and request body
include::{snippets}/register-success/http-request.adoc[]

And the response will be
include::{snippets}/register-success/http-response.adoc[]

==== Invalid request
Here's all the invalid requests and their respective response

*Bad token*

Sample Request
include::{snippets}/register-invalid-token/http-request.adoc[]

And the response will be
include::{snippets}/register-invalid-token/http-response.adoc[]

*Bad param*

Sample Request with application name longer than 32 character
include::{snippets}/register-invalid-body/http-request.adoc[]

And the response will be
include::{snippets}/register-invalid-body/http-response.adoc[]

=== Read Application
Here's how to get application details by providing _application id_

include::{snippets}/get-log-success/http-request.adoc[]

And the response will be

include::{snippets}/get-log-success/http-response.adoc[]

[[log]]
== Logs
This service is used to add a new log for an existing application

[[log-valid-request]]
=== Valid request
Access the log service using valid token and request body
include::{snippets}/log-success/http-request.adoc[]

And you will get the following response
include::{snippets}/log-success/http-response.adoc[]

[[log-invalid-request]]
=== Invalid request
Here's few of the invalid request and their respective response for log service

[[log-invalid-request-app-id]]
==== Application id
Below making an request with invalid application id
include::{snippets}/log-fail-invalid-app-id/http-request.adoc[]

And the response will be
include::{snippets}/log-fail-invalid-app-id/http-response.adoc[]

[[log-invalid-request-content-lenght]]
==== Content length
Here's a request to log service with extra long logger
include::{snippets}/log-fail-invalid-content-length/http-request.adoc[]

and the response will be
include::{snippets}/log-fail-invalid-content-length/http-response.adoc[]